[package]
name = "ci"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
colored = "3.0.0"
glob = "0.3.2"
hcl-rs = "0.18.5"
ignore = "0.4.23"
log = "0.4.27"
serde = "1.0.219"
walkdir = "2.5.0"
